<?php

namespace AppBundle\Repository;

/**
 * ReglagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglagesRepository extends \Doctrine\ORM\EntityRepository
{
}
